# Fichier: .streamlit/config.toml

[theme]
base = "dark"
primaryColor = "#3b82f6"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f1f5f9"
font = "sans serif"

[client]
toolbarMode = "viewer" # Cache le menu hamburger pour les visiteurs
showErrorDetails = false
